import type { MetadataRoute } from 'next'
import { SITE_URL } from '@/lib/site-config'

/**
 * /robots.txt — generated by Next.js at build time from this route.
 *
 * Rules:
 *  - All well-behaved crawlers (Googlebot, Bingbot, AI crawlers, etc.) are allowed.
 *  - /admin and /api are blocked from indexing (admin UI is internal; API is JSON).
 *  - The sitemap is published and self-referenced here.
 *
 * Audit reference: docs/seo-audit-2026-07-05/01-technical-seo.md §Top 5 #1
 *                  docs/seo-audit-2026-07-05/00-summary-report.md §Tier 1 #1
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin', '/admin/*', '/api', '/api/*'],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  }
}