import type { MetadataRoute } from 'next'
import { getPosts } from '@/lib/wordpress'
import { SITE_URL, proxyWpImage } from '@/lib/site-config'

/**
 * /sitemap.xml — generated by Next.js at build time.
 *
 * Strategy:
 *  - All static top-level pages (/, /about, /books, /contact, /podcast,
 *    /resources, /blog) are listed directly.
 *  - All WordPress blog posts (up to 100 latest) are pulled from the WP REST
 *    API and listed with their lastModified date.
 *  - Per-post lastModified uses the WP `modified` field so editors can
 *    re-prioritize fresh content via standard WP workflows.
 *
 * Audit reference: docs/seo-audit-2026-07-05/01-technical-seo.md §Quick Win #1
 *                  docs/seo-audit-2026-07-05/00-summary-report.md §Tier 1 #2
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const staticPaths = ['', '/about', '/books', '/contact', '/podcast', '/resources', '/blog']

  const staticEntries: MetadataRoute.Sitemap = staticPaths.map((p) => ({
    url: `${SITE_URL}${p}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: p === '' ? 1.0 : 0.8,
  }))

  let postEntries: MetadataRoute.Sitemap = []
  try {
    const { posts } = await getPosts(1, 100)
    postEntries = posts
      .filter((p) => p?.slug && p?.date)
      .map((p) => ({
        url: `${SITE_URL}/blog/${p.slug}`,
        lastModified: new Date(p.modified || p.date),
        changeFrequency: 'monthly',
        priority: 0.6,
      }))
  } catch (err) {
    // If WP is unreachable, ship the sitemap with only static entries rather
    // than failing the build. The audit caught this — sitemap absence is a
    // worse outcome than a sitemap without blog posts.
    console.warn('[sitemap] Could not fetch WP posts; serving static-only sitemap.', err)
  }

  return [...staticEntries, ...postEntries]
}